export enum NotificationType {
  // Recruiter - Individual Candidate Processing
  NEW_APPLICATION = 'NEW_APPLICATION',
  STATUS_CHANGE = 'STATUS_CHANGE',
  AI_ANALYSIS_COMPLETE = 'AI_ANALYSIS_COMPLETE',
  PROCESSING_FAILED = 'PROCESSING_FAILED',
  CANDIDATE_SHORTLISTED = 'CANDIDATE_SHORTLISTED',
  BIAS_ALERT = 'BIAS_ALERT',
  DUPLICATE_CANDIDATE = 'DUPLICATE_CANDIDATE',
  
  // Recruiter - Bulk Operations
  BULK_PROCESSING_COMPLETE = 'BULK_PROCESSING_COMPLETE',
  
  // Admin - System Health
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SECURITY_ALERT = 'SECURITY_ALERT',
  HEALTH_METRICS_ALERT = 'HEALTH_METRICS_ALERT',
  PERFORMANCE_DEGRADATION = 'PERFORMANCE_DEGRADATION',
  
  // Admin - Business Intelligence
  USER_MILESTONE_REACHED = 'USER_MILESTONE_REACHED',
  PROCESSING_MILESTONE = 'PROCESSING_MILESTONE',
  MONTHLY_ANALYTICS_REPORT = 'MONTHLY_ANALYTICS_REPORT',
}